
[theme]

# The preset Streamlit theme that your custom theme inherits from.
# This can be one of the following: "light" or "dark".
base = "light"

# Primary accent color.
primaryColor ="#117170"

# Background color of the app.
##backgroundColor ="#ffffff"

# Background color used for most interactive widgets.
secondaryBackgroundColor ="#eeeeee"

# Color used for almost all text.
textColor ="#1d1d1d"

# Color used for all links.
##linkColor ="rgb(255, 217, 0)"

# Background color used for code blocks.
##codeBackgroundColor ="rgb(240, 96, 0)"

# The font family for all text, except code blocks. This can be one of
# the following:
# - "satisfy"
# - "serif"
# - "monospace"
# - the `family` value for a custom font table under [[theme.fontFaces]]
# - a comma-separated list of these (as a single string) to specify
#   fallbacks
# For example, you can use the following:
# font = "cool-font, fallback-cool-font, sans-serif"
##font =

# The font family to use for code (monospace) in the sidebar. This can be
# one of the following:
# - "sans-serif"
# - "serif"
# - "monospace"
# - the `family` value for a custom font table under [[theme.fontFaces]]
# - a comma-separated list of these (as a single string) to specify
#   fallbacks
##codeFont =

# The font family to use for headings. This can be one of the following:
# - "sans-serif"
# - "serif"
# - "monospace"
# - the `family` value for a custom font table under [[theme.fontFaces]]
# - a comma-separated list of these (as a single string) to specify
#   fallbacks
# If no heading font is set, Streamlit uses `theme.font` for headings.
##headingFont =

# An array of fonts to use in your app. Each font in the array is a table
# (dictionary) with the following three attributes: family, url, weight,
# and style. To host a font with your app, enable static file serving
# with `server.enableStaticServing=true`. You can define multiple
# [[theme.fontFaces]] tables.
# For example, each font is defined in a [[theme.fontFaces]] table as
# follows:
# [[theme.fontFaces]]
# family = "font_name"
# url = "app/static/font_file.woff"
# weight = 400
# style = "normal"
##fontFaces =

# The radius used as basis for the corners of most UI elements. This can
# be one of the following: "none", "small", "medium", "large", "full",
# or the number in pixels or rem. For example, you can use "10px",
# "0.5rem", or "2rem". To follow best practices, use rem instead of
# pixels when specifying a numeric size.
##baseRadius =

# The color of the border around elements.
##borderColor =

# Whether to show a border around input widgets.
##showWidgetBorder =

# Sets the root font size (in pixels) for the app, which determines the
# overall scale of text and UI elements. The default base font size is 16.
##baseFontSize =

# Whether to show a vertical separator between the sidebar and the main
# content area.
##showSidebarBorder =



#[client]
#showSidebarNavigation = true

#[menuItems]
# Lien vers ton portfolio ou une page d’info
#about = "https://www.letskaw.com/portfolio"
# Pour proposer un lien de bug report personnalisé
#reportBug = "https://github.com/letskaw/lets_hub/issues"
# Pour proposer un lien vers la doc ou autre
#getHelp = "https://www.letskaw.com/porfolio"
